### ISSUE TITLE
Correggere "telegram_events.py" per rilevamento GIF

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/mozitaantispam_bot#20]
Telegram ha modificato gli eventi e le GIF, al momento, sono rilevate come "Documento".

Possibile soluzione:
Riga `84` (attuale): elif ("document" in msg) and (("D" in allowed_events) or all_events):
Riga `84` (soluzione): elif ("document" in msg) and not ("animation" in msg) and (("D" in allowed_events) or all_events):

**Comment by ilyasmg** [comment]
lo aggiungo io
